config:
  port: 8000
  basePath: /api

routes:
  - method: GET
    route: /posts
    service: localhost:3000
    path: /posts
    mapping:
      - path: /comments?postId={id}
        service: localhost:3000
        tag: comments
        removeKeyMapping: false
      - path: /api/users/{userId}
        service: localhost:8000
        tag: user
        removeKeyMapping: true

  - method: GET
    route: /users/{userId}
    service: localhost:3000
    path: /users/{userId}
    mapping:
      - path: /companies?id={companyId}
        service: localhost:3000
        tag: company
        removeKeyMapping: true

  - method: GET
    route: /companies
    service: localhost:3000
    path: /companies
    mapping:
      - path: /users?companyId={id}
        service: localhost:3000
        tag: users
        removeKeyMapping: true

  - method: GET
    route: /companies/{companyId}/users
    service: localhost:3000
    path: /users?companyId={companyId}

  - method: GET
    route: /companies/{companyId}
    service: localhost:3000
    path: /companies/{companyId}
    mapping:
      - path: /users?companyId={id}
        service: localhost:3000
        tag: users
        removeKeyMapping: false

  - method: GET
    route: /sse
    service: localhost:3000
    path: /sse
    isSSE: true


