config:
  port: 8000
  basePath: /api

routes:
  - method: GET
    route: /posts
    path: /posts
    service: localhost:3000
    mapping:
      - path: /comments?postId={id}
        service: localhost:3000
        tag: comments
        removeKeyMapping: false
      - path: /users/{userId}
        service: localhost:3000
        tag: user
        removeKeyMapping: true
